### ISSUE TITLE
broken link to horizontal grid index documentation

### ISSUE THREAD

**Issue by StephenGriffies** [raphaeldussin/MOM6-AnalysisCookbook#14]
This link to horizontal grid index documentation is broken.  I do not know where the correct link is.  

https://github.com/raphaeldussin/MOM6-AnalysisCookbook/blob/3cf066aefe3d37e1ed57d8817f30e229138b366b/docs/notebooks/getting_started.ipynb#L19

**Comment by raphaeldussin** [comment]
fix by #18
