### ISSUE TITLE
What does drop_variables do?  

### ISSUE THREAD

**Issue by StephenGriffies** [raphaeldussin/MOM6-AnalysisCookbook#15]
Three variables are "drop_variables".  I presume that means these variables are ignored.  But please explain the reasoning.  A google search turned up "drop_vars" but not "drop_variables".  It would be useful to offer a one-sentence explanation. 

https://github.com/raphaeldussin/MOM6-AnalysisCookbook/blob/3cf066aefe3d37e1ed57d8817f30e229138b366b/docs/notebooks/getting_started.ipynb#L62-L64

**Comment by jetesdal** [comment]
`drop_variables` is an optional parameter used in `xarray.open_dataset()` function. See https://docs.xarray.dev/en/stable/generated/xarray.open_dataset.html
> drop_variables ([str](https://docs.python.org/3/library/stdtypes.html#str) or [iterable](https://docs.python.org/3/glossary.html#term-iterable) of [str](https://docs.python.org/3/library/stdtypes.html#str), optional) – A variable or list of variables to exclude from being parsed from the dataset. This may be useful to drop variables with problems or inconsistent values.

I am not sure if 'average_DT', 'average_T1' and 'average_T2' need to be ignored when loading the data. I think it is more to keep the variable list in the xarray dataset "tidy".
